//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.11 at 04:55:05 PM GMT+03:00 
//


package by.epam.lw05.files.medicines;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Consistense.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Consistense">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pill"/>
 *     &lt;enumeration value="capsule"/>
 *     &lt;enumeration value="drops"/>
 *     &lt;enumeration value="ointment"/>
 *     &lt;enumeration value="syrup"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Consistense")
@XmlEnum
public enum Consistense {

    @XmlEnumValue("pill")
    PILL("pill"),
    @XmlEnumValue("capsule")
    CAPSULE("capsule"),
    @XmlEnumValue("drops")
    DROPS("drops"),
    @XmlEnumValue("ointment")
    OINTMENT("ointment"),
    @XmlEnumValue("syrup")
    SYRUP("syrup");
    private final String value;

    Consistense(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Consistense fromValue(String v) {
        for (Consistense c: Consistense.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
