//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.11 at 04:55:05 PM GMT+03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.files.lw05.epam.by/Medicines", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.epam.lw05.files.medicines;
